test_the_tester: Added assert_errcode, added die function, refactoring to use die function.

diff --git a/scripts/tests/test_the_tester/common b/scripts/tests/test_the_tester/common
--- a/scripts/tests/test_the_tester/common
+++ b/scripts/tests/test_the_tester/common
@@ -7,22 +7,60 @@ TEST_HELPERS="${TEST_DIR}/test_helpers"
 #It will not work in ANY other shell.
 declare -a arr_actual
 declare -a arr_expected
+
+
+#This function is only intended to called in the event
+#an error occurs that will impede the effectiveness of this
+#test suite. It is not to be called when running the
+#test suite in the event of input failing the test in
+#question.  That's because test failure is expected,
+#and is not a reason to halt all operations. In that
+#case, we return a non-zero error code and let execution
+#continue
+function die {
+   [ $# -lt 2 ] && >&2 echo "die: Too few arguments" && exit 1
+   [ $# -gt 2 ] && >&2 echo "die: Too many arguments" && exit 1
+
+   local func_name=$1
+   local message=$2
+   >&2 echo "${func_name}:${message}"
+   exit 1 
+}
+
+function __arrs_exist {
+    [ ! $# -lt 1 ] && die "__arrs_exist" "Too few arguments."
+    [ ! $# -gt 1 ] && die "__arrs_exist" "Too many arguments"
+
+    [ "$(set -o posix; set | grep -i 'arr_actual')" == "" ] || \
+    [ "$(set -o posix; set | grep -i 'arr_expected')" == "" ]; && \ 
+    return 1
+    return 0
+}
+
 function assert_correct_by_output_and_errcode {
     #Make sure arr_actual and arr_expected exist
     #and have values:
-    if [ "$(set -o posix; set | grep -i 'arr_actual')" == "" ] ||
-       [ "$(set -o posix; set | grep -i 'arr_expected')" == ""]; then
-        echo "One or more of either \"arr_actual\" and \"arr_expected\""
-        echo "is not set. This function requires these arrays."
-        echo "Please create them."
-    fi
+
+    #Fix this logic to properly use the "die" function
+    ! __arrs_exist  && die \
+    "assert_correct_by_output_and_errcode" \
+    "One or more of \"arr_actual\" and \"arr_expected\" \
+    is not set. This function requires these arrays. \
+    Please create them." && \
+    return 1
+
     local actual_size="${#arr_actual[@]}"
     local expected_size="${#arr_expected[@]}"
 
     #Make sure the arrays have values:
-    if [ ${}  ]; then
-
+    if [ ${actual_size} -eq 0 ] ||
+       [ ${expected_size} -eq 0 ]; then
+       echo "One or more of \"arr_actual\" and \"arr_expected\""
+       echo "does (do) not have values. Both arrays must be populated"
+       echo "for this function to work. Returing now."
+       return 1
     fi
+
     function __print_comparison {
         echo
         echo
@@ -32,7 +70,7 @@ function assert_correct_by_output_and_errcode {
         echo
         echo "# Values:"
         echo "######################################"
-        for var in ${arr_expected}; do
+        for var in ${arr_expected[@]}; do
             echo "${var}"
         done
         echo
@@ -44,7 +82,7 @@ function assert_correct_by_output_and_errcode {
         echo
         echo "# Values:"
         echo "######################################"
-        for var in ${arr_actual}; do
+        for var in ${arr_actual[@]}; do
             echo "${var}"
         done
         echo
@@ -84,3 +122,25 @@ function assert_correct_by_output_and_errcode {
         __counter=$((__counter + 1))
     done
 }
+
+function assert_errcode {
+    [ $# -lt 1  ] && die "assert_errcode" "Too few arguments"
+    [ ${#} -gt 1  ] && die "assert_errcode" "Error. Too many arguments."
+
+    if ! __arrs_exist;  then
+
+    fi
+
+    local __expected_code=$1
+    #Make sure that arr_actual has output.
+}
+
+
+#Populate the arrays.
+function populate_output_arr_with_output {
+    for var in ${@}; do
+        arr_output+=("${var}")
+    done
+}
+
+
